"""
Veras los tipos de variables que hay, Revisa el cuaderno para ver cuales hay 
    y su explicacion de su función
"""
from ctypes.wintypes import BOOL
from dataclasses import dataclass
a = str("Hola")
b = int(4)
c = float(1.23)
d = complex(3j)
e = list(["Manzana", "Banana", "Uva"])
f = tuple(("Carne", "Hueso", "Pollo"))
g = range(6)
h = dict({"Name": "John", "Age": "36"})
i = set({"Colombiana", "Pepsi", "Coca-cola"})
j = frozenset({"Colombi", "Pep", "Coca"})
k = bool() #si esta vacio sera false y si tiene un numero es true
l = bytes(6)
m = bytearray(bytes(l))
n = memoryview(bytes(l))

print("Variables de data")
print("-------------------------------------------------")
print("Datas")
print("-------------------------------------------------")
print(a)
print(type(a))
print("-------------------------------------------------")
print(b)
print(type(b))
print("-------------------------------------------------")
print(c)
print(type(c))
print("-------------------------------------------------")
print(d)
print(type(d))
print("-------------------------------------------------")
print(e)
print(type(e))
print("-------------------------------------------------")
print(f)
print(type(f))
print("-------------------------------------------------")
print(g)
print(type(g))
print("-------------------------------------------------")
print(h)
print(type(h))
print("-------------------------------------------------")
print(i)
print(type(i))
print("-------------------------------------------------")
print(j)
print(type(j))
print("-------------------------------------------------")
print(k)
print(type(k))
print("-------------------------------------------------")
print(l)
print(type(l))
print("-------------------------------------------------")
print(m)
print(type(m))
print("-------------------------------------------------")
print(n)
print(type(n))
